# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=relay3
      - MYSQL_ROOT_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080